# Rep from => https://github.com/shephertz/App42PaaS-Java-MySQL-Sample
# Result => http://35.246.162.237:8088/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT
version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: core
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 12345
    networks:
      - net-app

  collector:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - application-vol:/home/source/App42PaaS-Java-MySQL-Sample/target/
      - properties-vol:/home/source/App42PaaS-Java-MySQL-Sample/WebContent/

  prod:
    image: tomcat:8.5
    ports:
      - "8088:8080"
    volumes:
      - application-vol:/usr/local/tomcat/webapps/
      - properties-vol:/usr/local/tomcat/ROOT/
    depends_on:
      - db
    networks:
      - net-app

volumes:
  application-vol:
  properties-vol:
networks:
  net-app: